version: '3.9'
services:
  mysql:
    env_file:
      - ./docker/db/.db.env
    image: mysql:8.0
    ports:
      - "3320:3306"
    volumes:
      - ./docker/db/scripts/:/docker-entrypoint-initdb.d
      - ./docker/db/conf:/etc/mysql/conf.d
  redis:
    image: redis
    ports:
      - "6380:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
