spring:
  config:
    activate:
      on-profile: storage
  datasource:
    url: jdbc:mysql://localhost:3306/taskbuddy
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
